climatepolicyradar/navigator-admin-frontend

src/api/index.ts

This has not been tested - but this change should use the env var `API_URL` for making calls to the API and not the hardcoded staging - tho this is still used by default

Use ENV for api url

---

src/api/Documents.ts
src/api/Families.ts
src/components/lists/CollectionList.tsx
src/components/lists/DocumentList.tsx
src/components/lists/FamilyList.tsx
src/views/collection/Collections.tsx
src/views/dashboard/Dashboard.tsx

- Default search removed, to allow blank query
- Remove "click here" copy when not a link
- Add empty list handling for Families, Documents, Collections

Remove default search, incorrect copy, handling empty lists

---

src/components/lists/FamilyList.tsx
src/utils/getStatusAlias.ts

Create an alias function to rename the status for "DELETED" families to "NO DOCUMENTS" instead.
Manually tested only

PDCT-721/change_deleted_text_for_no_documents

---

.eslintrc.cjs
src/api/Documents.ts
src/components/forms/DocumentForm.tsx
src/hooks/useConfig.ts
src/interfaces/Config.ts
src/interfaces/Document.ts
src/schemas/documentSchema.ts
src/tests/components/forms/DocumentForm.test.tsx
src/tests/utils/modifyConfig.test.ts
src/tests/utilsTest/mocks.tsx
src/tests/utilsTest/render.tsx
src/utils/configureConfig.ts
src/utils/modifyConfig.ts
tsconfig.json

Features:
1. Replace language selector for chakra one (allowing filter by typing).
2. Create new attribute of Config for sorted languages.
3. Store the sorted languages in Cache for rendering only first time.
4. Create architecture for component tests (wrappers and mocks).
5. Create unit and component testing for covering this solution.
Problems:
chrakra-react-select is a weird component hard to test (there are not documentation, no examples in stackoverflow and no tests inside of the library 💀). I wasn't able to test it as fully as I had hoped.

PDCT-720 Use chakra react select and sort the language list using cache

---

src/components/forms/FamilyForm.tsx
src/components/lists/FamilyList.tsx
src/tests/components/forms/FamilyForm.test.tsx
src/tests/components/lists/FamilyList.test.tsx
src/tests/utilsTest/mocks.tsx

- Alert icon for buttons in FamilyForm if there is not Documents or Events.
- Alert icon in FamilyList if there is Documents or Events empty (NO Documents AND NO Events)
Notes:
brackets and …

Pdct 831/family will not get published alert

---

src/components/forms/FamilyForm.tsx

Fix the use of the blocker
Notes:

PDCT-968/bug_create_family_trigger_modal_always

---

.github/pull_request_template.md
.github/workflows/ci-cd.yml

Add auto-tagging failsafe to CI
Notes:

Pdct 851/fail the auto tagging build during a pr if no semver boxes ticked

---

.github/workflows/ci-cd.yml

Use always() and ! cancelled() to avoid uncancellable workflows
Notes:

Use always() and ! cancelled() to avoid uncancellable workflows

---

src/components/buttons/Delete.tsx
src/components/family/FamilyDocument.tsx
src/components/family/FamilyEvent.tsx
src/components/forms/DocumentForm.tsx
src/components/forms/EventForm.tsx
src/components/forms/FamilyForm.tsx
src/components/lists/FamilyList.tsx
src/tests/components/lists/FamilyList.test.tsx
src/tests/utilsTest/mocks.tsx
src/utils/canModify.ts

[PDCT-1104](https://linear.app/climate-policy-radar/issue/PDCT-1104/block-frontend-crud-if-org-mismatch) 
Block CRUD when org mismatch.
Notes:

Disable/hide CRUD buttons if org mismatch

---

src/components/forms/FamilyForm.tsx

- Driveby add check if dirty to summary field
- Move modal out of form submit context
Notes:

Pdct 968/bug create family trigger modal always

---

src/components/family/FamilyDocument.tsx
src/components/forms/DocumentForm.tsx
src/interfaces/Document.ts
src/tests/components/forms/DocumentForm.test.tsx

- Remove references to document type on DTO
Notes:

Remove references to document type on DTO

---

src/components/form-components/WYSIWYG.tsx

- Revert the change to the WYSIWYG and remove the stripPastedStyles prop
Notes:

Revert the change to the WYSIWYG stripPastedStyles

---

src/views/document/Document.tsx

Document view was missing any check to `canModify` which resulted in the form never being able to be saved. I have used the same logic from the family view.
Notes:

Add the canModify control to the document-level view

---

src/components/drawers/DocumentEditDrawer.tsx
src/components/drawers/EventEditDrawer.tsx
src/components/family/FamilyDocument.tsx
src/components/forms/FamilyForm.tsx
src/components/lists/FamilyEventList.tsx
src/hooks/useDocument.ts
src/tests/components/drawers/EventEditDrawer.test.tsx
src/tests/mocks/handlers.ts
src/tests/mocks/repository.ts
src/tests/utilsTest/mocks.tsx
src/tests/views/Family.test.tsx

- fixed document not updating on Family page after editing
- added test to reproduce the bug
- refactored Drawer components for editing events and documents
Notes:

Pdct 985/update loaded family document after edit

---

src/components/forms/CollectionForm.tsx

- removed Organisation field and radio buttons from the Collections form (both create and edit) as they should not be entered/editable by the user
Notes:

Remove Organisation radio buttons from Collections form

---

src/components/forms/CollectionForm.tsx
src/interfaces/Collection.ts
src/routes/collectionRoutes.tsx
src/routes/index.tsx
src/schemas/collectionSchema.ts
src/tests/mocks/api/collectionHandlers.ts
src/tests/mocks/api/documentHandlers.ts
src/tests/mocks/api/eventHandlers.ts
src/tests/mocks/api/familyHandlers.ts
src/tests/mocks/handlers.ts
src/tests/mocks/repository.ts
src/tests/utilsTest/mocks.tsx
src/tests/utilsTest/renderRoute.tsx
src/tests/views/Collections.test.tsx

- removed organisation radio buttons from the Collection form (both create and edit) as the value should be taken from the user context
- do not send the organisation field when creating a collection as it is not used in the backend
- added a test to cover creating of a new collection
Notes:
- If you are selecting the version in the list …

Pdct 1221/remove vestige of organisation

---

src/components/forms/FamilyForm.tsx
src/utils/stripHtml.ts

- Adding validation on the WYSIWYG field, this involves stripping out the HTML tags in order to check if the field is empty.
Notes:

PDCT 1456 : validation of wysiwyg summary field

---

.github/workflows/ci-cd.yml

Use v16 reusable workflows
Notes:

Use v16 reusable workflows

---

src/components/forms/DocumentForm.tsx
src/components/forms/EventForm.tsx
src/hooks/useTaxonomy.ts
src/interfaces/Config.ts
src/interfaces/Document.ts
src/schemas/documentSchema.ts
src/tests/components/forms/DocumentForm.test.tsx
src/tests/utilsTest/mocks.tsx

Fix - document form parses mcf data/taxonomy without erroring
Notes:

Fix cannot edit mcf docs on admin frontend

---

src/components/forms/metadata-handlers/familyForm.ts
src/interfaces/Family.ts
src/interfaces/Metadata.ts

Add GEF metadata rendering for families
Notes:

Add GEF metadata rendering for families

---

src/components/forms/DynamicMetadataFields.tsx
src/components/forms/FamilyForm.tsx
src/components/forms/fields/TextField.tsx
src/components/forms/sections/MetadataSection.tsx

Fix uncontrolled controlled bug in dynamic metadata form
Notes:

Fix uncontrolled controlled bug in dynamic metadata form

---

src/components/forms/metadata-handlers/familyForm.ts

Make sure finances are sent to API as string
Notes:

Make sure finances are sent to API as string

---

src/components/forms/DynamicMetadataFields.tsx
src/components/forms/fields/SelectField.tsx

Fix form label ordering issue
From 
To
Notes:

Fix form label ordering issue

---

src/components/forms/FamilyForm.tsx
src/components/forms/fields/TextField.tsx

- Resolves the javascript error in the console when on the family form (this should also resolve any issue related to the text input fields that have a similar error)
- Also contains drive-by fix for displaying metadata when creating a new family
Notes:
sure …

Default TextField to empty string value if non passed

---

src/components/forms/DocumentForm.tsx
src/components/forms/FamilyForm.tsx
src/interfaces/Document.ts
src/interfaces/Metadata.ts
src/schemas/documentSchema.ts

Updates to the admin front
- driveby refactors
- fix: approved_ref was expecting num types instead of text/string
- feat: set url as required on documents for mcf corpora projects 
- feat: set default author type and author values for mcf guidances
Notes:
sure …

Feature/app 160 UI updates to the admin frontend mcf guidances

---

src/api/Families.ts
src/components/lists/FamilyList.tsx

Adds support for displaying and filtering by multiple geographies on the families page:
- Added support for multiple `geography` params, which matches how the API is called with multiple geographies e.g. `?geography=United+Kingdom&geography=Ireland`.
- The geographies column shows a ChakraUI badge for each geography code (ISO 3166-1 Alpha-3), alphabetically sorted for consistency.
- Updated the geographies filter to accept multiple geographies, store them in state, and apply them to queries being made.
- Known issue: The page loads after each change to the geographies filter, so it can take a moment to add multiple geographies. This could be fixed in the future (or insisted on by the reviewer now).
- Results show OR logic matches - if a family includes any of the filtered geographies, it …

APP-177: Make geography filter on family list page support multi geos

---

src/components/forms/DocumentForm.tsx

- our backend parsing/queries retrieve and filter the language model based on the language name and we are sending the language code, when trying to update the language specifically it fails at this[ function](https://github.com/climatepolicyradar/navigator-admin-backend/blob/e7ecee08f63924bf8173bb7fd7037d47a6aac103/app/repository/document.py#L357).
Updating the payload to use the language name (label) instead of the code (value) resolves this. 
Notes:
- If none of these options are selected, auto-tagging will …

Fix: Document update fails with status code 503 when changing language

---

src/api/CorpusTypes.ts
src/components/SideMenu.tsx
src/components/forms/CorpusTypeForm.tsx
src/components/lists/CorpusTypeList.tsx
src/hooks/useCorpusType.ts
src/interfaces/CorpusType.ts
src/routes/index.tsx
src/schemas/corpusSchema.ts
src/schemas/corpusTypeSchema.ts
src/tests/components/lists/CorpusTypeList.test.tsx
src/views/corpusTypes/CorpusType.tsx
src/views/corpusTypes/CorpusTypes.tsx

Read corpus type information via admin service UI for superusers.
Notes:

Feature/app 55 read corpus type information via admin service UI

---

src/api/Organisations.ts
src/components/SideMenu.tsx
src/components/forms/CorpusTypeForm.tsx
src/components/forms/OrganisationForm.tsx
src/components/lists/OrganisationList.tsx
src/hooks/useOrganisation.ts
src/routes/index.tsx
src/schemas/organisationSchema.ts
src/tests/components/lists/OrganisationList.tsx
src/views/organisation/Organisation.tsx
src/views/organisation/Organisations.tsx

Add basic organisation /all and /get rendering for superuser s in the admin frontend. Create and update deliberate left unimplemented.
This has helped me identify some dodgy org description values -- where `'null'` is stored instead of an actual null value in the database.
Notes:
- If you are selecting the version in the list above using …

Feature/app 216 Show all organisations in the admin UI for superusers

---

.env.example
package.json
src/interfaces/Family.ts
src/tests/components/lists/FamilyList.test.tsx
src/tests/helpers.ts
src/tests/mocks/api/configHandlers.ts
src/tests/mocks/api/familyHandlers.ts
src/tests/mocks/repository.ts
src/tests/setup.js
src/tests/utilsTest/mocks.tsx
src/tests/views/FamilyCreate.test.tsx
yarn.lock

- extend the FamilyCreate.test.tsx to submit the form
- add an npm script to run tests without mock service worker (so that they run against a real API and not mocked API)
Notes:
brackets …

Enable running tests against mock and local API

---

src/components/forms/FamilyForm.tsx
src/tests/components/forms/CorpusForm.test.tsx
src/tests/utils/stripHtml.test.ts
src/utils/stripHtml.ts

Addresses a bug where HTML markup is too aggressively stripped from the family summary when the page is saved. This happens before sending an API request. Instead, this PR introduces some sympathetic allowances to increase the ease of copy/paste from documents.
- Added `stripHtmlForRichText` utility:
- Replacing HTML tags uses a `String.match` function for greater control over what the replacement text is.
- Tags listed in the `ALLOWED_TAGS` array aren't stripped in their entirety anymore. This is links and some typographic styles including lists.
- Converts some tags listed in `REPLACE_TAGS` so that they match the HTML tags being used by `draft-js` (WYSIWYG text editor).
- Strip `style` attributes from all tags to purge any word processor styling copied across.
- Tests for …

APP-210: Bug: Hyperlinks in Family summary disappeared once the entries were published

---

src/api/AppToken.ts
src/components/SideMenu.tsx
src/components/forms/AppTokenForm.tsx
src/components/forms/fields/TextField.tsx
src/components/lists/CorpusList.tsx
src/hooks/useCorpora.ts
src/interfaces/AppToken.ts
src/routes/index.tsx
src/schemas/appTokenSchema.ts

Create app tokens via admin service UI (superuser only).
- Users can create from scratch
- Users can create using an existing token as a template
Notes:

Feature/app 229 create app tokens via admin service UI

---

src/components/forms/fields/TextField.tsx

The formatting for the form helper text on the TextField component has been wrong for literally months. This closes off an ancient ticket.

Feature/app 199 fix form helper text for textfield formatting 
